### ISSUE TITLE
Questions about the tutorial

### ISSUE THREAD

**Issue by pchiang5** [const-ae/glmGamPoi#11]
Hi Constantin,

Thank you for the great tool.

Could you kindly explain the language you used in the tutorial?

```
fit <- glm_gp(sce_subset, design = ~ cell + stim +  stim:cell - 1,
              reference_level = "NK cells")
```
1. Why there is a "-1" in the "design"? Did it mean the "NK cells' in the "reference_level", or the default 1-coefficient fitting?

2. Is there any advantage of including the "reference_level" here(instead of reference_level=NULL and excluding NK cells in the dataset)? 
 
```
de_res <- test_de(fit, contrast = `stimstim` + `cellCD4 T cells:stimstim`, 
                  pseudobulk_by = paste0(stim, "-", ind)) 
```
3. Did "contrast = `stimstim` + `cellCD4 T cells:stimstim`"  indicate the contrast between `stimstim` of all stimulated cell types (actually normalized B and T by the reference NK cells) and `cellCD4 T cells:stimstim` of stimulated T cells alone?

```
marker_genes2 <- test_de(fit, (`cellCD4 T cells` + `cellCD4 T cells:stimstim`) - 
                               (`cellB cells` + `cellB cells:stimstim`), 
                        sort_by = pval)
```

4. Can I replace the ```(`cellCD4 T cells` + `cellCD4 T cells:stimstim`) -  (`cellB cells` + `cellB cells:stimstim`)``` with ```(`stimstim`  + `cellCD4 T cells:stimstim`) -  (`stimstim` + `cellB cells:stimstim`)``` and reach the identical output?

Thank you

Po

**Comment by const-ae** [comment]
Hi Po,

> Why there is a "-1" in the "design"?

The `-1` remove the intercept. If you want to learn more about how model matrices work and how they are generated, check out the [ExploreModelMatrix](http://bioconductor.org/packages/release/bioc/vignettes/ExploreModelMatrix/inst/doc/ExploreModelMatrix.html) package. I also wrote a similar package, which is less polished, but might still be helpful to understand how linear models work https://github.com/const-ae/CoefExplainer.

> Is there any advantage of including the "reference_level" here

This partially to demonstrate how the interface works and what options are available. But also keep in mind that even without an intercept, the reference level still influences the interaction term.

> Did "contrast = stimstim + cellCD4 T cells:stimstim" indicate the contrast between stimstim of all stimulated cell types (actually normalized B and T by the reference NK cells) and cellCD4 T cells:stimstim of stimulated T cells alone?

No. `stimstim + cellCD4 T cells:stimstim` is the estimated difference between the control CD4 T-cells and the stimulated CD4 T-cells. 

I think the best way to look at this is to look at an example with the CoefExplainer package:

```{r}
# To understand what these two lines do, we select an example gene 
# and analyze the coefficients with the CoefExplainer package
fit <- glm_gp(sce_subset, design = ~ cell + stim +  stim:cell - 1)
de_res <- test_de(fit, contrast = `stimstim` + `cellCD4 T cells:stimstim`) 

# Add counts to data.frame, because that is the necessary input format
colData(fit$data)$y <- counts(sce_subset)["PSME2", ]
ce <- CoefExplainer::CoefExplainer(colData(fit$data), formula = y ~ cell + stim +  stim:cell - 1)
CoefExplainer::plotAll(ce)
```

![image](https://user-images.githubusercontent.com/5359014/100078745-20ed2b80-2e44-11eb-88ca-e7e146896e3b.png)

As you can, to go from the control CD4 T-cells you need both the `stimstim` and the `cellCD4 T cells:stimstim` coefficients.

> Can I replace the (`cellCD4 T cells` + `cellCD4 T cells:stimstim`) - (`cellB cells` + `cellB cells:stimstim`) with (`stimstim` + `cellCD4 T cells:stimstim`) - (`stimstim` + `cellB cells:stimstim`) and reach the identical output?

The best way to find out such things, is to just run it and see ;)  However, note that `(`stimstim` + `cellCD4 T cells:stimstim`) - (`stimstim` + `cellB cells:stimstim`)` is equal to `(`cellCD4 T cells:stimstim`) - (`cellB cells:stimstim`)`, so answer is going to be no :)

**Comment by pchiang5** [comment]
Many thanks, Constantin. The CoefExplainer and ExploreModelMatrix are what I really need to understand the proper inputs into `design` and `contrast`.
