### ISSUE TITLE
size_factors = FALSE in README

### ISSUE THREAD

**Issue by jeffreypullin** [const-ae/glmGamPoi#3]
In the README there is the comment + code: 

```r
# size_factors = FALSE, because only a single GLM is fitted
fit <- glm_gp(counts, design = ~ 1)
fit
```

I interpreted the comment as an explanation of why the following code sets `size_factors = FALSE` but then the code doesn't do this. 

Is this an oversight or have I misinterpreted the comment?

Best!

**Comment by const-ae** [comment]
Oh, you are absolutely right this was an oversight on my side. I changed the behavior to not estimate a size factor if there is only one gene a month ago https://github.com/const-ae/glmGamPoi/commit/b1f8666aeef6bfe2ffb05b3036de8e1bf885a1e3 and apparently forgot to update the README :)

**Comment by jeffreypullin** [comment]
Thanks for the quick fix!
