### ISSUE TITLE
Unable to install the glmGamPoi package

### ISSUE THREAD

**Issue by Kravidc** [const-ae/glmGamPoi#57]
Dear Team,

I am trying to install the glmGamPoi package as it was recommended for seurat V5. I seem to be running into trouble at some place. I am not sure how to resolve this. Could you please help me with the same?
The code and output on the RConsole is given below: 

Machine details: MacOS: Sonoma 14.1.1 - Intel i7 2020 Macbook Pro

Thank You!

> if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

> BiocManager::install("glmGamPoi")

Do you want to attempt to install these from sources? (Yes/no/cancel) Yes
trying URL 'https://bioconductor.org/packages/3.18/bioc/src/contrib/glmGamPoi_1.14.0.tar.gz'
Content type 'application/x-gzip' length 2104349 bytes (2.0 MB)
==================================================
downloaded 2.0 MB

* installing *source* package ‘glmGamPoi’ ...
** using staged installation
** libs
using C++ compiler: ‘Apple clang version 15.0.0 (clang-1500.0.40.1)’
using C++11
using SDK: ‘MacOSX14.0.sdk’
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/ -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/beachmat/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/ -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/beachmat/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c beta_estimation.cpp -o beta_estimation.o
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/ -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/beachmat/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c deviance.cpp -o deviance.o
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/ -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/beachmat/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c overdispersion.cpp -o overdispersion.o
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/ -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/beachmat/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c utils.cpp -o utils.o
clang++ -arch x86_64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/x86_64/lib -o glmGamPoi.so RcppExports.o beta_estimation.o deviance.o overdispersion.o utils.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: search path '/opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0' not found
ld: warning: search path '/opt/gfortran/lib' not found
ld: library 'gfortran' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [glmGamPoi.so] Error 1
ERROR: compilation failed for package ‘glmGamPoi’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/glmGamPoi’

The downloaded source packages are in
	‘/private/var/folders/f_/0_5sprfx4zd_h_r8ppr1mjf00000gr/T/RtmpuS99mM/downloaded_packages’
Update all/some/none? [a/s/n]: 
a
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/stringi_1.8.1.tgz'
Content type 'application/x-gzip' length 14625717 bytes (13.9 MB)
==================================================
downloaded 13.9 MB

The downloaded binary packages are in
	/var/folders/f_/0_5sprfx4zd_h_r8ppr1mjf00000gr/T//RtmpuS99mM/downloaded_packages

> library(glmGamPoi)

Error in library(glmGamPoi) : there is no package called ‘glmGamPoi’

**Comment by const-ae** [comment]
Hi Kravidc,

sorry for the problems that you encountered and thanks for posting the full error, which helps a lot diagnosing the problem. The important line is:

> ld: library 'gfortran' not found

R tries to build `glmGamPoi` from source, which means that you need make sure that the required compilers are available. There is a helpful overview page from CRAN at https://mac.r-project.org/tools/ listing a number of tools and the best practices for installing them.

In particular, you will need to follow the instructions at https://github.com/R-macos/gcc-12-branch/releases to install `gfortran`.

Let me know, if this resolves the issue or if you encounter further issues.

Best,
Constantin

**Comment by Kravidc** [comment]
Hi Constantin,

Thank you for the quick response! 
I was able to install the mandatory tools mentioned in the first link you shared, and this allowed me to install the glmGamPoi package.

Thanks a lot!

Best regards,
Kaushikk

**Comment by const-ae** [comment]
That's excellent.
