### ISSUE TITLE
Missing test_de Function

### ISSUE THREAD

**Issue by nicholaslimwy** [const-ae/glmGamPoi#9]
Hi Constantin,

Apologies for having to open another issue so soon! I've tried running test_de and it doesn't appear to be part of glmGamPoi from Bioconductor, I've tried separately adding the function via the source code (including eval_with_q and handle_design_parameter). It also appears that colData is called on a $data column, but I encounter an error that it doesn't exist when trying to run it. 

```
Error in value[[3L]](cond) : unable to find an inherited method for function ‘colData’ for signature ‘"NULL"’
8.
stop(e$message)
7.
value[[3L]](cond)
6.
tryCatchOne(expr, names, parentenv, handlers[[1L]])
5.
tryCatchList(expr, classes, parentenv, handlers)
4.
tryCatch({ res <- eval(statement, envir = as.list(data), enclos = statement_envir) if (!is.numeric(res)) { if (is.character(res) && length(res) == 1) { ...
3.
eval_with_q(pseudobulk_by, SummarizedExperiment::colData(fit$data), env = env)
2.
test_de_q(fit, contrast = contrast_capture, reduced_design = reduced_design, full_design = full_design, subset_to = subset_to_capture, pseudobulk_by = pseudobulk_by_capture, pval_adjust_method = pval_adjust_method, sort_by = sort_by_capture, decreasing = decreasing, n_max = n_max, ...
1.
test_de(fit, reduced_design = ~1)
```
Thanks!
Nick

**Comment by const-ae** [comment]
Hi Nick,

> I've tried running test_de and it doesn't appear to be part of glmGamPoi from Bioconducto

yes, you are right. I added the `test_de` function after the last Bioconductor release (https://github.com/const-ae/glmGamPoi/blob/master/NEWS#L21), so it will only become available from Bioconductor in November after the Biocondutor 3.12 release.

I would recommend instead of sourcing individual files, to install the development version of the package using `devtools`:

```
devtools::install_github("const-ae/glmGamPoi")
```

This gives you the latest version of the package, including all features that are described by the README.

Let me know if this solves your problem :)

**Comment by nicholaslimwy** [comment]
Hi Constantin,

Yes it does! Upon running the DE function I'm getting really high lfc values despite using the normalized counts from my Seurat object. Might you have any suggestions to normalize the lfc too?

**Comment by const-ae** [comment]
I am not sure, that I correctly understand what you mean. But you should not call `glmGamPoi` with the normalized values from Seurat, but with the raw count matrix!

> Might you have any suggestions to normalize the lfc too?

I currently don't implement any LFC shrinkage in glmGamPoi, but DESeq2 does and the latest version of DESeq2 (which you can get with `devtools::install_github("mikelove/DESeq2")`) can call `glmGamPoi` internally. You could for example call `DESeq2::DESeq(..., fitType = "glmGamPoi")` to fit the model with glmGamPoi and then call `DESeq2::lfcShrink()` to get shrunken LFC estimates.

**Comment by nicholaslimwy** [comment]
Ah sorry, had a massive brain fart there! No, I'm using the raw counts. I've used the lfcShrink function in DESeq2 and it works well, thanks again for the help.

**Comment by const-ae** [comment]
No problem. Glad that you were able to solve the problem :)
